# Auto-generated by tools/partition_layout.py --gen-list from boards.toml.
# Do not edit by hand; add/remove mcuboot boards in tools/boards.toml and
# re-run `python3 tools/partition_layout.py --gen-list`.
#
# Boards whose layout boots via mcuboot (Adaboot). sysbuild builds a mcuboot
# image for these and applies their dts/<vendor>/<board>.dtsi overlay
# to both the mcuboot and application images. Boards NOT in this list run
# standalone (no mcuboot domain) -- their overlay is applied to the app only.
set(MCUBOOT_BOARDS
    da14695_dk_usb
    ek_ra6m5
    ek_ra8d1
    frdm_mcxn947
    frdm_rw612
    mimxrt1170_evk
    nrf5340dk
    nrf54h20dk
    nrf54l15dk
    nrf7002dk
    nucleo_n657x0_q
    nucleo_u575zi_q
    stm32h7b3i_dk
    stm32wba65i_dk1
    CACHE INTERNAL "Boards that boot via mcuboot (per this fork's boards.toml)"
)
