# Auto-generated make fragment for nrf7002dk (slot layout).
# Generated by tools/partition_layout.py; do not edit by hand --
# re-run `python3 tools/partition_layout.py --fix nrf7002dk` after
# changing the layout. Consumed by host tooling that builds .uf2
# files: Adaboot's UF2 writer routes blocks by target address, so
# a .uf2's target addresses start at the app slot's offset within
# its flash device. Blocks aimed at partitions on other flash
# devices are addressed at their natural device offset and must
# carry the partition-name extension tag instead.
MCUBOOT_UF2_APP_BASE := 0x11000
