# Auto-generated make fragment for nucleo_n657x0_q (slot layout).
# Generated by tools/partition_layout.py; do not edit by hand --
# re-run `python3 tools/partition_layout.py --fix nucleo_n657x0_q` after
# changing the layout. Consumed by host tooling that builds .uf2
# files: Adaboot's UF2 writer routes blocks by flash-area offset, so
# a .uf2's target addresses start at the app slot's offset within
# its flash device.
MCUBOOT_UF2_APP_BASE := 0x40000
