# Auto-generated make fragment for siwx917_dk2605a (slot layout).
# Generated by tools/partition_layout.py; do not edit by hand --
# re-run `python3 tools/partition_layout.py --fix siwx917_dk2605a` after
# changing the layout. Consumed by host tooling that builds .uf2
# files: Adaboot's UF2 writer routes blocks by flash-area offset, so
# a .uf2's target addresses start at the app slot's offset within
# its flash device.
MCUBOOT_UF2_APP_BASE := 0x222000
